### ISSUE TITLE
 tree_ft.sh file does not exist 

### ISSUE THREAD

**Issue by youngDouble** [roblanf/sarscov2phylo#19]
Version: release 13-11-20
I noticed that the` tree_ft.sh` file does not exist in the scripts folder
`scripts/global_tree_gisaid.sh:
        bash $DIR/tree_ft.sh -i $outputfasta -t $threads`
Where can I get `tree_ft.sh` ?

**Comment by AngieHinrichs** [comment]
tree_ft.sh was removed in 55cbb8ddaddaceb2ecd0577f105a3fd37f13d304.  You can make a fork of this repo in Github, clone your fork on the command line and bring back the script with 'git revert 55cbb8dd'.

**Comment by roblanf** [comment]
Thanks @AngieHinrichs. 

@youngDouble: to add a bit more detail, the repo contains a few old scripts that I no longer use. In particular, I used to build the tree from scratch at every update, but I moved to iteratively improving the tree instead because this is a better approach (in terms of speed and accuracy) for this situation where we get a small amount of new data every day. `tree_ft.sh` is one of those older scripts that I did remove.

However, you're not the first person that has wanted to use that, so I'll give a bit of thought to how best to clean up the repo so it includes clear information on both:

1. De-novo phylogenetics for SARS-CoV-2 (i.e. starting from scratch each time)
2. Online phylogenetics (which is what the readme runs through).

Thoughts welcome.

Rob

**Comment by youngDouble** [comment]
> tree_ft.sh was removed in [55cbb8d](https://github.com/roblanf/sarscov2phylo/commit/55cbb8ddaddaceb2ecd0577f105a3fd37f13d304). You can make a fork of this repo in Github, clone your fork on the command line and bring back the script with 'git revert [55cbb8d](https://github.com/roblanf/sarscov2phylo/commit/55cbb8ddaddaceb2ecd0577f105a3fd37f13d304)'.
